version: "3"
services:
 web:
  build: .
  environment:
   - NODE_ENV=development
  ports:
   - "1337:1337"
  command: npm run dev
  volumes:
   - ./:/usr/src/app
 db:
   image: mysql:5.7
   environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=resizer
     - MYSQL_DATABASE_URL=mysql:root@mysql:3306/resizer
   volumes:
     - ./_docker/mysql:/var/lib/mysql
