version: "3"
services:
 web:
  build: .
  environment:
   - NODE_ENV=development
   - MYSQL_DATABASE_URL=mysql://root:root@db:3306/resizer
   - REDIS_DATABASE_URL=redis://redis
  ports:
   - "1337:1337"
  command: npm run dev
  volumes:
   - ./:/usr/src/app
 db:
   image: mysql:5.7
   environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=resizer
   volumes:
     - ./_docker/mysql:/var/lib/mysql
 redis:
   image: redis:5.0
